//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net.MVC5_TatilSeyehatSitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBLOGCOMMENTS
    {
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string MAIL { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> BLOGID { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual TBLBLOG TBLBLOG { get; set; }
    }
}
