//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net.MVC5_TatilSeyehatSitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBLOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBLOG()
        {
            this.TBLBLOGCOMMENTS = new HashSet<TBLBLOGCOMMENTS>();
        }
    
        public int ID { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string DESCRIPTOIN { get; set; }
        public string IMAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBLOGCOMMENTS> TBLBLOGCOMMENTS { get; set; }
    }
}
