//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net.MVC5_TatilSeyehatSitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCONTACT
    {
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string PHONE2 { get; set; }
        public string EMAIL2 { get; set; }
        public string FAX2 { get; set; }
        public string LOCATION { get; set; }
    }
}
